# coding: utf-8

# flake8: noqa
"""
    Healthcare Appointment Booking System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from openapi_client.models.appointment_create import AppointmentCreate
from openapi_client.models.appointment_response import AppointmentResponse
from openapi_client.models.appointment_update import AppointmentUpdate
from openapi_client.models.doctor_create import DoctorCreate
from openapi_client.models.doctor_response import DoctorResponse
from openapi_client.models.doctor_update import DoctorUpdate
from openapi_client.models.feedback_create import FeedbackCreate
from openapi_client.models.feedback_response import FeedbackResponse
from openapi_client.models.http_validation_error import HTTPValidationError
from openapi_client.models.location_inner import LocationInner
from openapi_client.models.token import Token
from openapi_client.models.user_create import UserCreate
from openapi_client.models.user_login import UserLogin
from openapi_client.models.validation_error import ValidationError

