# coding: utf-8

# flake8: noqa

"""
    Healthcare Appointment Booking System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "AppointmentsApi",
    "AuthApi",
    "DefaultApi",
    "DoctorsApi",
    "FeedbacksApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AppointmentCreate",
    "AppointmentResponse",
    "AppointmentUpdate",
    "DoctorCreate",
    "DoctorResponse",
    "DoctorUpdate",
    "FeedbackCreate",
    "FeedbackResponse",
    "HTTPValidationError",
    "LocationInner",
    "Token",
    "UserCreate",
    "UserLogin",
    "ValidationError",
]

# import apis into sdk package
from openapi_client.api.appointments_api import AppointmentsApi as AppointmentsApi
from openapi_client.api.auth_api import AuthApi as AuthApi
from openapi_client.api.default_api import DefaultApi as DefaultApi
from openapi_client.api.doctors_api import DoctorsApi as DoctorsApi
from openapi_client.api.feedbacks_api import FeedbacksApi as FeedbacksApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.appointment_create import AppointmentCreate as AppointmentCreate
from openapi_client.models.appointment_response import AppointmentResponse as AppointmentResponse
from openapi_client.models.appointment_update import AppointmentUpdate as AppointmentUpdate
from openapi_client.models.doctor_create import DoctorCreate as DoctorCreate
from openapi_client.models.doctor_response import DoctorResponse as DoctorResponse
from openapi_client.models.doctor_update import DoctorUpdate as DoctorUpdate
from openapi_client.models.feedback_create import FeedbackCreate as FeedbackCreate
from openapi_client.models.feedback_response import FeedbackResponse as FeedbackResponse
from openapi_client.models.http_validation_error import HTTPValidationError as HTTPValidationError
from openapi_client.models.location_inner import LocationInner as LocationInner
from openapi_client.models.token import Token as Token
from openapi_client.models.user_create import UserCreate as UserCreate
from openapi_client.models.user_login import UserLogin as UserLogin
from openapi_client.models.validation_error import ValidationError as ValidationError

