# coding: utf-8

"""
    Healthcare Appointment Booking System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.feedback_response import FeedbackResponse

class TestFeedbackResponse(unittest.TestCase):
    """FeedbackResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FeedbackResponse:
        """Test FeedbackResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FeedbackResponse`
        """
        model = FeedbackResponse()
        if include_optional:
            return FeedbackResponse(
                id = 56,
                doctor_id = 56,
                patient_name = '',
                rating = 56,
                comment = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return FeedbackResponse(
                id = 56,
                doctor_id = 56,
                patient_name = '',
                rating = 56,
                comment = '',
        )
        """

    def testFeedbackResponse(self):
        """Test FeedbackResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
