# coding: utf-8

"""
    Healthcare Appointment Booking System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.auth_api import AuthApi


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthApi()

    def tearDown(self) -> None:
        pass

    def test_login_auth_login_post(self) -> None:
        """Test case for login_auth_login_post

        Login
        """
        pass

    def test_register_auth_register_post(self) -> None:
        """Test case for register_auth_register_post

        Register
        """
        pass


if __name__ == '__main__':
    unittest.main()
