# coding: utf-8

"""
    Healthcare Appointment Booking System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.doctor_update import DoctorUpdate

class TestDoctorUpdate(unittest.TestCase):
    """DoctorUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DoctorUpdate:
        """Test DoctorUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DoctorUpdate`
        """
        model = DoctorUpdate()
        if include_optional:
            return DoctorUpdate(
                is_available = True
            )
        else:
            return DoctorUpdate(
                is_available = True,
        )
        """

    def testDoctorUpdate(self):
        """Test DoctorUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
