# coding: utf-8

"""
    Healthcare Appointment Booking System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.feedbacks_api import FeedbacksApi


class TestFeedbacksApi(unittest.TestCase):
    """FeedbacksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FeedbacksApi()

    def tearDown(self) -> None:
        pass

    def test_get_doctor_feedbacks_feedbacks_doctor_id_get(self) -> None:
        """Test case for get_doctor_feedbacks_feedbacks_doctor_id_get

        Get Doctor Feedbacks
        """
        pass

    def test_leave_feedback_feedbacks_post(self) -> None:
        """Test case for leave_feedback_feedbacks_post

        Leave Feedback
        """
        pass

    def test_list_feedbacks_feedbacks_get(self) -> None:
        """Test case for list_feedbacks_feedbacks_get

        List Feedbacks
        """
        pass


if __name__ == '__main__':
    unittest.main()
