# coding: utf-8

"""
    Healthcare Appointment Booking System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.appointments_api import AppointmentsApi


class TestAppointmentsApi(unittest.TestCase):
    """AppointmentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AppointmentsApi()

    def tearDown(self) -> None:
        pass

    def test_book_appointment_appointments_post(self) -> None:
        """Test case for book_appointment_appointments_post

        Book Appointment
        """
        pass

    def test_cancel_appointment_appointments_id_delete(self) -> None:
        """Test case for cancel_appointment_appointments_id_delete

        Cancel Appointment
        """
        pass

    def test_list_appointments_appointments_get(self) -> None:
        """Test case for list_appointments_appointments_get

        List Appointments
        """
        pass

    def test_update_appointment_status_appointments_id_patch(self) -> None:
        """Test case for update_appointment_status_appointments_id_patch

        Update Appointment Status
        """
        pass


if __name__ == '__main__':
    unittest.main()
