# coding: utf-8

"""
    Healthcare Appointment Booking System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.doctors_api import DoctorsApi


class TestDoctorsApi(unittest.TestCase):
    """DoctorsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DoctorsApi()

    def tearDown(self) -> None:
        pass

    def test_create_doctor_doctors_post(self) -> None:
        """Test case for create_doctor_doctors_post

        Create Doctor
        """
        pass

    def test_get_doctor_booked_slots_doctors_id_booked_slots_get(self) -> None:
        """Test case for get_doctor_booked_slots_doctors_id_booked_slots_get

        Get Doctor Booked Slots
        """
        pass

    def test_get_doctors_doctors_get(self) -> None:
        """Test case for get_doctors_doctors_get

        Get Doctors
        """
        pass

    def test_get_my_doctor_profile_doctors_me_get(self) -> None:
        """Test case for get_my_doctor_profile_doctors_me_get

        Get My Doctor Profile
        """
        pass

    def test_update_doctor_availability_admin_doctors_id_patch(self) -> None:
        """Test case for update_doctor_availability_admin_doctors_id_patch

        Update Doctor Availability Admin
        """
        pass

    def test_update_my_doctor_profile_doctors_me_patch(self) -> None:
        """Test case for update_my_doctor_profile_doctors_me_patch

        Update My Doctor Profile
        """
        pass


if __name__ == '__main__':
    unittest.main()
