# coding: utf-8

"""
    Healthcare Appointment Booking System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.appointment_update import AppointmentUpdate

class TestAppointmentUpdate(unittest.TestCase):
    """AppointmentUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppointmentUpdate:
        """Test AppointmentUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppointmentUpdate`
        """
        model = AppointmentUpdate()
        if include_optional:
            return AppointmentUpdate(
                status = 'completed'
            )
        else:
            return AppointmentUpdate(
                status = 'completed',
        )
        """

    def testAppointmentUpdate(self):
        """Test AppointmentUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
