# coding: utf-8

"""
    Healthcare Appointment Booking System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.feedback_create import FeedbackCreate

class TestFeedbackCreate(unittest.TestCase):
    """FeedbackCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FeedbackCreate:
        """Test FeedbackCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FeedbackCreate`
        """
        model = FeedbackCreate()
        if include_optional:
            return FeedbackCreate(
                doctor_id = 56,
                rating = 1.0,
                comment = ''
            )
        else:
            return FeedbackCreate(
                doctor_id = 56,
                rating = 1.0,
                comment = '',
        )
        """

    def testFeedbackCreate(self):
        """Test FeedbackCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
